---
- name: Setup Development Workstation
  connection: local
  become: yes
  hosts: 127.0.0.1

  pre_tasks:
    - name: Do we wish to install xrdp
      set_fact:
        xrdp: false

  roles: 
    - common
    - packages
    - kvm
    - docker
    #- repositories
    # - users
    