---
# Install docker packages

- name: Add repository
  yum_repository:
    name: docker
    description: Docker CE repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

- name: Install docker packages
  yum: name={{ item }} state=latest
  with_items:
      - yum-utils 
      - device-mapper-persistent-data
      - lvm2
      - docker-ce

- name: enable docker
  systemd:
    state: started
    enabled: yes
    name: docker
